/*=======================================================================*\
|| ###################################################################### ||
|| # vBulletin 5.2.3
|| # ------------------------------------------------------------------ # ||
|| # Copyright 2000-2016 vBulletin Solutions Inc. All Rights Reserved.  # ||
|| # This file may not be redistributed in whole or significant part.   # ||
|| # ----------------- VBULLETIN IS NOT FREE SOFTWARE ----------------- # ||
|| # http://www.vbulletin.com | http://www.vbulletin.com/license.html   # ||
|| ###################################################################### ||
\*========================================================================*/
window.vBulletin=window.vBulletin||{};window.vBulletin.phrase=window.vBulletin.phrase||{};window.vBulletin.phrase.precache=window.vBulletin.phrase.precache||[];window.vBulletin.phrase.precache=$.merge(window.vBulletin.phrase.precache,[]);window.vBulletin.options=window.vBulletin.options||{};window.vBulletin.options.precache=window.vBulletin.options.precache||[];window.vBulletin.options.precache=$.merge(window.vBulletin.options.precache,[]);(function(C){var A={};function B(){C(function(){var D=[];C(".js-content-slider").each(function(){var L=C(this);D.push(L.attr("id"));var K=L.closest(".js-content-slider-wrapper").innerWidth();L.width(K);L.find(".js-content-slider__slides").width(K);var G=L.data("config-height");G=parseInt(G,10);if(G>0){L.height(G);L.find(".js-content-slider__slides").height(G);var I=L.find(".js-content-slider__slide-caption-background").outerHeight();if(G>I){var F=parseInt(G*0.15,10)}else{var F=0}var E=F+5,H=F,J=F+2;L.find(".js-content-slider__slide-caption").css("bottom",E+"px");L.find(".js-content-slider__slide-caption-background").css("bottom",H+"px");L.find(".js-content-slider__arrow").css("bottom",J+"px")}});C.each(D,function(){var E=this,H=C("#"+E),F=H.data("config-interval");F=(C.isNumeric(F)?Math.floor(F*1000):3000);var G={$AutoPlay:true,$AutoPlayInterval:F,$Idle:F,$SlideDuration:650,$ArrowKeyNavigation:true,$PauseOnHover:1,$BulletNavigatorOptions:{$Class:$JssorBulletNavigator$,$ChanceToShow:2,$ActionMode:1,$AutoCenter:0,$Orientation:1},$ArrowNavigatorOptions:{$Class:$JssorArrowNavigator$,$ChanceToShow:1,$AutoCenter:0,$Steps:1}};A[E]=new $JssorSlider$(E,G)});C(".js-content-slider").each(function(){var I=C(this);var E=I.data("config-height");E=parseInt(E,10);if(E>0&&E<120){var K=I.find(".js-content-slider__arrow--right");var J=C("html").attr("dir")=="ltr";var G=J?"right":"left";var F=parseInt(K.css(G),10);var H=I.find(".js-content-slider__bullets").outerWidth();K.css(G,(H+(F*2)))}});C(".js-content-slider__slide").each(function(){var F=C(this),E=F.find(".js-content-slider__link");F.on("click",function(H){var G=C(H.target);if(G.is(".b-content-slider__slide, .b-content-slider__title, .ellipsis")){document.location.href=E.attr("href")}})});C(".js-content-slider-wrapper").hide().removeClass("b-content-slider__wrapper--hidden").fadeIn("slow")})}window.vBulletin=window.vBulletin||{};window.vBulletin.contentslider=window.vBulletin.contentslider||{};vBulletin.contentslider.handleWindowResize=function(){C(".js-content-slider").each(function(){var G=C(this),F=G.closest(".js-content-slider-wrapper");var E=F.innerWidth();F.find("> .js-content-slider > div").width(E);G.width(E);G.find(".js-content-slider__slides").width(E);G.find(".b-content-slider__slide").width(E);var D=G.attr("id");if(A&&typeof A[D]!="undefined"){A[D].$ScaleWidth(E)}})};B()})(jQuery);